// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI9MUaev1E8FX3ag2yjMrqK5qpanyKQk0',
    appId: '1:84522726569:web:dfa385390da065b88be5b8',
    messagingSenderId: '84522726569',
    projectId: 'fan-technical-mdtest',
    authDomain: 'fan-technical-mdtest.firebaseapp.com',
    storageBucket: 'fan-technical-mdtest.firebasestorage.app',
    measurementId: 'G-JZ0D2HH958',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTCx28OyTbGJTHJ0sjqucta3Y0niDxT3o',
    appId: '1:84522726569:android:83bb50d056d9dc1f8be5b8',
    messagingSenderId: '84522726569',
    projectId: 'fan-technical-mdtest',
    storageBucket: 'fan-technical-mdtest.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmzj8trpSDDxeLGuGFGhlegr_0w2PhIho',
    appId: '1:84522726569:ios:7753968ce9d7dc3b8be5b8',
    messagingSenderId: '84522726569',
    projectId: 'fan-technical-mdtest',
    storageBucket: 'fan-technical-mdtest.firebasestorage.app',
    iosBundleId: 'com.example.fanTechnicalMdtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI9MUaev1E8FX3ag2yjMrqK5qpanyKQk0',
    appId: '1:84522726569:web:8a2affefe49dca0e8be5b8',
    messagingSenderId: '84522726569',
    projectId: 'fan-technical-mdtest',
    authDomain: 'fan-technical-mdtest.firebaseapp.com',
    storageBucket: 'fan-technical-mdtest.firebasestorage.app',
    measurementId: 'G-YVXCGLRBYJ',
  );
}
